inherit_from: [configs/dataset/config_base_3RScan_orbslam_l20.yaml, configs/method/config_base_JointSSG.yaml]
model:
 multi_rel: false # multiple relationship 
 use_JointSG: false
 use_msg: true
 use_BCE: false
 lambda_trans: 0.4
 lambda_scale: 0.4
wandb:
 tags: ["ssg", "jointSSG",'orbslam','l20']
name: 'draw'